version: '3'
services:
  jenkins:
    build:
      context: ./jenkins
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - GITHUB_EP=${GITHUB_EP}
    volumes:
      - p-jenkins-home:/var/jenkins_home
    ports:
      - 8080:8080
    env_file:
      .env
volumes:
  p-jenkins-home:
  
