pipeline {
    agent any
    parameters {
        string(name: "BACKUP_FILE_NAME", defaultValue: "", description: "s3上のバックアップファイル名")
        booleanParam(name: "CHECKOUT_ONLY", defaultValue: true, description: "Jenkinsfileのパラメータ反映用です。trueにするとJenkinsfileのfetchだけを行い、ジョブは中断します")
    }
    
    options {
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        // パラメータ反映のための空振り用
        stage('Fetch Params') {
            when {
                expression {
                    return params.CHECKOUT_ONLY
                }
            }
            steps {
                script {
                    currentBuild.description = "for fetching parameters"
                }
                sh 'exit 1'
            }
        }

        stage("Restore") {
            steps {
                sh './jenkins/scripts/restore.sh $BACKUP_FILE_NAME'
            }
        }
    }
    
    post {
        always {
            script {
                // 後から理解しやすいようにビルドの詳細を書き換えましょう
                currentBuild.description = "CHECKOUT_ONLY=$CHECKOUT_ONLY"
            }
        }
    }

}
